server:
  port: 8766
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/